spec/dry/data/constrained_spec.rb
spec/dry/data/default_spec.rb
spec/dry/data/enum_spec.rb
spec/dry/data/safe_spec.rb
spec/dry/data/sum_type_spec.rb
spec/dry/data/type/optional_spec.rb
spec/dry/data/type_spec.rb

@326bb2d649d94bb104ed99e96b8283cb48b25e62
The description of the spec stated it was testing #call yet the specs
were instead testing #[]. This change brings the spec description more
inline with other specs for #[].
@48707ab41b5a00ae3f49730c6169f33023b20d06
While the method is defined in #call the specs are testing the alias
of #[].
For the projects I'm considering using dry-data, I find the #call idiom to be
more inline with the projects existing idioms. So I want to see specs that
assert #call is part of the public interface and expectation.

Adding alias method verification for call

---

lib/dry/types/struct.rb

Prior to this commit, the code for Dry::Types::Schema.attributes was
doing the following (distilled into a more concrete example):
```ruby
prev_schema = schema || {}
def schema
@schema || {}
end
```
When expanded that looked something like the following:
```ruby
prev_schema = (@schema || {}) || {}
```
This change is meant to reduce the above to:
```ruby
prev_schema = @schema || {}
```

Removing duplication of logic

---

lib/dry/types/struct.rb
spec/dry/types/struct_spec.rb

As mentioned in the corresponding issue, schema checks were only skipped when the inheriting child did not define new attributes.
Fixes #62

Fix Struct grandchildren skipping schema checks

---

lib/dry/types/errors.rb
lib/dry/types/struct.rb
lib/dry/types/value.rb
spec/dry/types/struct_spec.rb
spec/shared/struct.rb

I'm using mutant to reveal which parts of `Dry::Types::Struct` are not covered by tests. So far I have addressed the following mutations with (somewhat) opinionated changes.
**1. `attr_reader` mutation**
Passing a key to `attr_reader` twice shouldn't matter in terms of behavior
or performance so I figured it was safe to make this change:
```diff
@@ -1,9 +1,9 @@
def self.attributes(new_schema)
prev_schema = schema
@schema = prev_schema.merge(new_schema)
@constructor = Types["coercible.hash"].public_send(constructor_type, schema)
-  attr_reader(*(new_schema.keys - prev_schema.keys))
+  attr_reader(*new_schema.keys)
equalizer.instance_variable_get("@keys").concat(schema.keys).uniq!
self
end
```
**2. non-unique `@keys` on `Struct`'s equalizer**
This mutation is more tricky. The current …

Improve test coverage for `Struct`, kill dead code, and tighten interface

---

lib/dry/types/maybe.rb

Actually after renaming Optional to Maybe we _can_ use nil as a default.
`Types::String.optional.default(nil)['foo'] => "foo"`

Update error message

---

lib/dry/types/coercions.rb
lib/dry/types/coercions/form.rb
lib/dry/types/coercions/json.rb
lib/dry/types/core.rb
spec/dry/types/types/form_spec.rb

These changes bring the `Form` coercions to 100% mutation coverage

Improve form test coverage

---

lib/dry/types/coercions/json.rb
lib/dry/types/definition.rb
spec/dry/types/definition_spec.rb

- 100% mutation coverage on `JSON.to_decimal`
- Brings mutation coverage of Result* up to 100% from 58.33%
- Specifies behavior of Definition#try
Result::Success and Result::Failure seem simple enough to assume that
they are implementation details so I tested the behavior through
Definition#try

Improve test coverage for `Result`, `Definition`, and `JSON.to_decimal`

---

lib/dry/types/struct.rb
spec/dry/types/struct_spec.rb

Previous behavior was
```ruby
class User < Dry::Types::Struct
constructor_type(:schema)
end
class Admin < User; end;
p User.constructor_type
=> :schema
p Admin.constructor_type
=> :strict
```
This PR makes sure `Admin`'s constructor type would be `:schema` here.

Inherit the constructor_type on Struct

---

lib/dry/types/compiler.rb
spec/dry/types/compiler_spec.rb

Fixes #74 
As I'm new to dry-types, I have very little overview if this could have negative impact elsewhere.

Fix compiler crash on empty hash schema, 74

---

Gemfile
lib/dry/types/builder.rb

This update makes use of the new predicate names from Dry-Logic
inclusion to included_in and exclusion to excluded_from.

Dry logic predicate change

---

lib/dry/types/coercions/form.rb
lib/dry/types/form.rb
spec/dry/types/types/form_spec.rb

This change makes it possible for forms to post blank arrays and hashes when the form post corresponds to dry-validation schema keys that are typed as arrays and hashes. You can do this with blank hidden inputs in your form, e.g.
```html
<input name="some_array" type="hidden">
<input name="some_hash" type="hidden">
```
Corresponding to a schema like this (from dry-validation master):
```ruby
Dry::Valiation.Form do
required(:some_array).each(:str?)
required(:some_hash).value(:hash?)
end
```
When this form is posted, these hidden inputs would come through as empty strings, which these new coercions will now turn into proper empty arrays and hashes.
This is useful because there is otherwise no way to signify in a form post that an array or hash value should be specified, but _empty_ (i.e. if …

Coerce empty strings in form posts to blank arrays and hashes

---

lib/dry/types/hashify.rb
lib/dry/types/struct.rb
spec/dry/types/struct_spec.rb

`Struct#to_hash` hashifies stuctures deeper (going inside arrays).
Suppose a struct has array attributes with struct members:
```
class User < Dry::Types::Struct
attribute :name, Types::Coercible::String
end
class Parent < User
attribute :children, Types::Array.member('user')
end
attributes = { name: 'Joe', children: [{ name: 'Jane' }] }
parent = Parent.new(attributes)
```
Old behaviour:
```
parent.to_hash # => { name: 'Joe', children: [#<User name="Jane">] }
```
New behaviour:
```
parent.to_hash # => { name: 'Joe', children: [{ name: 'Jane' }] }
```

Make Struct#to_hash go through arrays

---

lib/dry/types/struct.rb
lib/dry/types/struct/class_interface.rb
spec/shared/struct.rb

This add an interface of a type definition to Struct and Value and makes them work with `.|`, `.default`, `.enum`, and `.optional` methods for building new types. This is became a frequently requested feature and as far as I can tell nothing stops us from supporting it. A noticeable change is that Struct/Value subclasses are now registered in the container as is, we don't need to wrap them with a type definition anymore.
Any thoughts? /cc @solnic @AMHOL @timriley

Make Struct work as a type definition

---

lib/dry/types/decorator.rb
lib/dry/types/default.rb
lib/dry/types/options.rb
spec/dry/types/default_spec.rb
spec/dry/types/enum_spec.rb

Now Default type works nice with ROM's schema attribute which calls
`#with` on a passed type.
This also fixes the issue when a decorator type cannot have metadata.

Fix #with behavior with Default/Callable types

---

spec/dry/types_spec.rb

This PR tries to make a clear distinction of a constructor that calls the default _new_ methods and a constructor that calls a custom method (ex: build) differentiating them with a plain and an upcased result.

Improve dry/types_spec.rb

---

lib/dry/types/coercions/form.rb
spec/dry/types/types/form_spec.rb

* typecast `T` and `F` to boolean values (before we only accepted `t` and `f`)
* stringify boolean input values before passing them to map
The second thing may sound like it's not the case for `Form`, but here is my use case:
`Dry::Validation.Form` receives input from JSON parsed by Rails.
The clients sends the following JSON:
```json
{ "accept_the_rules": 0 }
```
which will be parsed by Rails JSON parser to
```ruby
{ "accept_the_rules" => 0 }
```
And `Dry::Validation.Form` will receive the integer value that it will try to typecast to boolean.
@solnic what do you think?

Improve form boolean casting

---

README.md

When I tried running `rake spec` without `bundle exec`, I just got this error:
~/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- dry/logic/rule_compiler (LoadError)

Fix the command to run tests in the README

---

lib/dry/types/core.rb

I was pointed to this problem by [Code Climate dry-rb/dry-types Issues](https://codeclimate.com/github/dry-rb/dry-types/issues), which listed two instances of “similar code” in this file.

Small refactoring to reduce duplication in core.rb

---

lib/dry/types/hash.rb
lib/dry/types/hash/schema.rb
spec/dry/types/compiler_spec.rb
spec/dry/types/hash_spec.rb

As part of the planned `constructor_type` transition the `strict`
schema is being renamed to `permissive` to make room for a more
strict schema type.
See: https://gitter.im/dry-rb/chat?at=57686358feaf6cd222ad7e15
Also from gitter:
> @backus proposal looks good except :permissive which shouldn’t use defaults, so I just want it to work exactly the same as current :strict - this is really important for the common case of building structs from db data that you expect to be valid

Rename Hash#strict to Hash#permissive

---

.travis.yml

> John Backus @backus Aug 30 16:26
> :skull: <-- me waiting for jruby-head to finish on CI
>
> Piotr Solnica @solnic Aug 30 16:32
> @backus I’d vote for removing jruby-head from all builds
> it’s been killing me too
>
> ...
>
> Tim Riley @timriley Aug 30 18:32
> oh yes, definitely +1 to removing jruby-head

Remove jruby-head from build

---

lib/dry/types/hash.rb
lib/dry/types/hash/schema.rb
spec/dry/types/hash_spec.rb

Following up on #134 and #135, this is the last of the constructor changes planned for dry-types for the sake of dry-struct. Just like the other PRs, see https://gitter.im/dry-rb/chat?at=57686358feaf6cd222ad7e15 as a reference for this work

Add `strict_with_defaults` constructor

---

lib/dry/types/hash/schema.rb
spec/dry/types/hash_spec.rb

All other hash schemas raise `SchemaError` except for the `:schema` constructor type. This change resolves this discrepancy

Fix #schema constructor raising different error

---

lib/dry/types/hash/schema.rb
spec/dry/types/hash_spec.rb

I can't believe I almost forgot this 😆. This is basically the entire reason I originally got involved in the hash schemas and dry-struct

Fix strict schemas accepting nil values when defaults are specified

---

CHANGELOG.md

It should be Dry::Types.load_extensions(:maybe) instead of Dry::Types.load_extension(:maybe).
See https://github.com/dry-rb/dry-types/blob/master/Rakefile#L11

Fixes typo in method spelling.

---

lib/dry/types/hash/schema.rb
spec/dry/types/hash/strict_with_defaults_spec.rb

Before fix:
```ruby
created_at = created_at: Dry::Types['strict.time'].default { Time.now }
hash = Dry::Types['hash'].strict_with_defaults(created_at: created_at)
hash.call.created_at.class # => Proc
```
After:
```ruby
hash.call.created_at.class # => Time
```

Evaluate proc values when resolving values in StrictWithDefaults constructor

---

lib/dry/types/definition.rb

Array splatting allocates memory unnecessarily because we know the exact
signatures of `Result::Success.new` and `Result::Error.new`.
As a bonus we improved the benchmarks a little bit.
Note the memory and perf **Before** and **After**:
* `271` vs `155` allocations
* `137121` vs `144956` i/s (for `schema#call`)
```
filename     type count old_count total_age min_age max_age total_memsize
dry/types/coercions/form.rb:23  T_IMEMO     1         0         0       0       0             0
dry/types/coercions/form.rb:26  T_IMEMO     1         0         0       0       0             0
dry/types/hash/schema.rb:96  T_IMEMO     1         0         0       0       0             0
dry/types/hash/schema.rb:138   T_HASH     4         0         0       0       0             0
dry/types/hash/schema.rb:92 …
```

Avoid array splatting in Types::Definition

---

.yardopts
Rakefile
dry-types.gemspec
lib/dry/types.rb
lib/dry/types/array.rb
lib/dry/types/array/member.rb
lib/dry/types/builder.rb
lib/dry/types/coercions.rb
lib/dry/types/coercions/form.rb
lib/dry/types/coercions/json.rb
lib/dry/types/constrained.rb
lib/dry/types/constrained/coercible.rb
lib/dry/types/constraints.rb
lib/dry/types/constructor.rb
lib/dry/types/decorator.rb
lib/dry/types/default.rb
lib/dry/types/definition.rb
lib/dry/types/enum.rb
lib/dry/types/errors.rb
lib/dry/types/extensions/maybe.rb
lib/dry/types/hash.rb
lib/dry/types/hash/schema.rb
lib/dry/types/options.rb
lib/dry/types/result.rb
lib/dry/types/safe.rb
lib/dry/types/sum.rb

I have started working on documenting `Dry::Types` internals. 
I found it much easier to understand the code and how `Dry::Types` are implemented internally. Also, it gives autocompletion for `Dry::Types`-enabled systems in RubyMine and maybe other IDEs.
What do you think about code documentation at all for `dry-` gems family? Would you like to merge this PR with documentation when I document more code?

YARD documentation for Dry::Types

---

CHANGELOG.md
lib/dry/types/core.rb
spec/dry/types/core_spec.rb

fixes #123
It's a small useful addition allows you to have a placeholder type that can be later constrained with an actual type check. It's also not so uncommon in a dynamically typed language to be in a situation where you just don't know beforehand an object of what type you're going to have. For instance, SQLite despite being a SQL database can return you data of any type it supports in any field of any row, and we have to deal with it.
/cc @solnic

Add Object type

---

lib/dry/types/hash.rb
lib/dry/types/options.rb
lib/spec/dry/types.rb
spec/dry/types/default_spec.rb

@solnic I did this because atm `type != type.meta({})` and this is obviously a bug. We need to store an empty hash for meta in options or not to store meta in options at all. I think the latter is better, what do you think about it? 
This allows to simplify code [like this](https://github.com/hanami/model/blob/ade8bf454f08f0bb066dc878aa962f20f11af299/lib/hanami/model/sql/types.rb#L37-L56) at least, while we don't have AST-transformations for types.

Do not store meta in options

---

CHANGELOG.md
lib/dry/types/any.rb
lib/dry/types/core.rb
spec/dry/types/core_spec.rb

@backus this fixes that issue with calling `valid?` on `BasicObject` descendants

Rename Object to Any

---

CHANGELOG.md
lib/dry/types/options.rb
lib/spec/dry/types.rb

This method resets `meta` and allows to compare types ignoring theirs metadata.
This is essentially comparison _by behavior_ rather than comparison _by value_.

Add Type#pristine

---

lib/dry/types/enum.rb
spec/dry/types/enum_spec.rb

Closes #189.
Wasn't sure whether to raise a custom error type or not - this PR just raises `RuntimeError`. Feel free to tweak the error message.
Note that this is a breaking change.

make .enum.default raise an error.

---

lib/dry/types/errors.rb
lib/dry/types/hash/schema.rb
spec/dry/types/hash_spec.rb

These fix https://github.com/dry-rb/dry-struct/issues/16
By passing the `result` message to error we will be able to access it in `dry-struct`

Pass result to schema error for improving error message

---

README.md

The README contains an outdated command to run the specs.
__Wrong__
```
bundle exec rake spec
```
__Correct__
```
bundle exec rake run_specs
```
There are at least these other commands, you can use to run the specs:
* `bundle exec rake` (because `run_specs` is set to be the default task)
* `bundle exec rspec`

Update README to contain correct command to run specs

---

lib/dry/types/sum.rb
spec/dry/types/sum_spec.rb

#184 
After checking the code looks like the `Sum` type was missing the `success` method, creating some errors using `dry-struct`.
This PR adds the `success` method.

Add success and failure method for Sum type

---

dry-types.gemspec
lib/dry/types.rb
lib/dry/types/errors.rb

As we talk about. 
This removes `dry-configurable` as a dependency.

Remove dry-configurable as dependency

---

lib/dry/types/default.rb
lib/dry/types/enum.rb
lib/dry/types/hash/schema.rb
spec/dry/types/default_spec.rb
spec/dry/types/enum_spec.rb
spec/dry/types/sum_spec.rb

This also changes the existing behavior regarding working with `nil`.
From now on when a default type gets `nil` it tries to pass it through
the wrapped type first and see if the output is `nil` or not. If it's
`nil` then the default value will be returned. The reason behind this change
is to make hash schemas simpler in presence of default values. The goal is
to always call a default type in a hash if the key is missing.
The behavior in presence of `nil` was dictated by backward compatibility,
we _may_ change it in future once it causes some unpredicted consequences.

Do not require value for default type

---

lib/dry/types.rb
lib/dry/types/builder.rb
lib/dry/types/compiler.rb
lib/dry/types/constructor.rb
lib/dry/types/default.rb
lib/dry/types/enum.rb
lib/dry/types/extensions/maybe.rb
lib/dry/types/hash.rb
lib/dry/types/hash/schema.rb
lib/dry/types/hash/schema_builder.rb
lib/dry/types/safe.rb
lib/dry/types/sum.rb
spec/dry/types/compiler_spec.rb
spec/dry/types/default_spec.rb
spec/dry/types/enum_spec.rb
spec/dry/types/hash_spec.rb
spec/dry/types/sum_spec.rb
spec/dry/types/to_ast_spec.rb

This branch depends on https://github.com/dry-rb/dry-types/pull/211
This is a promising start, the end goal is discarding hash schemas. I removed most of the code that relies on inheritance, the next step is removing inheritance altogether. I plan to provide backward compatibility for hash schemas, however, the main point is to provide enough flexibility for building custom-behavior schemas _without_ introducing a ton of barely compatible options. At the moment, I think we'll have to separate weak/symbolized schemas from other types.

Rework hash schemas

---

lib/dry/types/hash.rb
lib/dry/types/hash/schema.rb
lib/dry/types/hash/schema_builder.rb
spec/dry/types/hash_spec.rb
spec/dry/types/to_ast_spec.rb

This adds the following API for hash schemas:
1. `Schema#with_key_transform`—transforms keys of input hashes, for things like symbolizing etc.
1. `Schema#strict`—makes a schema intolerant to unknown keys.
1. `Hash#with_type_transform`—transforms member types with an arbitrary block. For instance, 
```ruby
optional_keys = Types::Hash.with_type_transform { |t| t.meta(omittable: true) }
schema = optional_keys.schema(name: 'strict.string', age: 'strict.int')
schema.(name: 'Jane') # => { name: 'Jane' }
```
From my perspective, these three methods is more than enough.

New API for hash schemas

---

lib/dry/types/builder.rb
lib/dry/types/enum.rb
spec/dry/types/enum_spec.rb

Allow to explicitly pass mapping between values and integer representation to enum. 
When working with legacy applications it may be useful to provide mapping between enum values and corresponding integer values.
``` ruby
Statuses = Types::Strict::String.enum('draft' => 0, 'published' => 10, 'archived' => 20)
Statuses[10] # => "published"
Statuses['published'] # => "published"
```
Passing values withot mapping works as well:
``` ruby
Statuses = Types::Strict::String.enum('draft', 'published', 'archived')
Statuses[1] # => "published"
Statuses['published'] # => "published"
```
Another problem is, lack of validation of integer values. So, you can create enum which maps Stings to Arrays for example.

Allow to explicitly pass mapping to enum

---

lib/dry/types/hash/schema.rb
spec/dry/types/hash_spec.rb

When using a coercible type and coercion fails, a `SchemaError` will now be raised and will indicate which key could not be coerced.

Types::Hash: Indicate which key could not be coerced properly

---

lib/dry/types/array/member.rb
spec/dry/types/array_spec.rb

This allows constructors to return `Undefined`, such values will be filtered out from the output array.

Filter out undefined values from arrays (fixes #208)

---

lib/dry/types/enum.rb
lib/dry/types/hash.rb
lib/dry/types/hash/schema.rb

There were some leftovers. Also:
- yard catches aliasing (as long as the original method is documented)
- yard automatically assigns boolean type as a return for ```?``` methods (see https://github.com/lsegal/yard/issues/1088)
- for aliases it does not detect param and gives a warning as stated below.
https://app.coditsu.io/dry-rb/builds/validations/72d10c0f-9ab3-4e5b-b673-ecf7f7a5dd74/offenses?q[offense_name_cont]=UnknownParameterName

yard doc fixes

---

lib/dry/types/builder_methods.rb
lib/dry/types/compiler.rb
lib/dry/types/core.rb
lib/dry/types/definition.rb
lib/dry/types/errors.rb
lib/dry/types/map.rb
lib/dry/types/options.rb
lib/dry/types/spec/types.rb
spec/dry/types/compiler_spec.rb
spec/dry/types/map_spec.rb
spec/dry/types/module_spec.rb

@flash-gordon 
implement a Map type based on the discussion from https://github.com/dry-rb/dry-types/issues/113
create one like:
```ruby
Dry::Types::Map.new(key_type: Dry::Types['strict.integer'], value_type: Dry::Types['strict.string'])
```
the empty<sup>[1]</sup> map is registered as `Dry::Types['map']` so you could also do:
```ruby
Dry::Types['map'].with(key_type: Dry::Types['strict.integer'], value_type: Dry::Types['strict.string'])
```
I chose to inherit from `Definition` as opposed to `Hash` to  avoid unintended interactions with the `Schema` logic
[1] by empty I mean unconstrained; any key-value pair is valid
_Edited to reflect the options renaming_

implement a Map type

---

lib/dry/types/default.rb
spec/dry/types/default_spec.rb

We had a strange behavior combining `default` and `meta`
```ruby
type = Dry::Types['hash'].default({}).meta(omittable: true)
type[] # => {:meta=>{:omittable=>true}}
```
With these changes works as expected 
```ruby
type = Dry::Types['hash'].default({}).meta(omittable: true)
type[] # => { }
```

Fix Default to allow accepting meta attributes

---

lib/dry/types/default.rb
spec/dry/types/default_spec.rb

@flash-gordon as we have spoken passing `Dry::Core::Constants::Undefined` as value to `#valid?` returns true

Ensure that #valid? returns true for Default type when passed Undefined as value.

---

lib/dry/types/constructor.rb
spec/dry/types/constrained_spec.rb
spec/dry/types/constructor_spec.rb
spec/dry/types/sum_spec.rb

This PR addresses the following incorrect behavior for `Constructor#valid?`, where a type with a constructor `fn` does not apply it to the value before checking its validity:
```ruby
BMI = Dry::Types['strict.int'].constrained(gteq: 18, lteq: 42).constructor { |x| x.round }
BMI[17.5]
#=> 18
BMI.valid?(17.5)
#=> false
```
After the changes, the call to `#valid?` above will return `true`.
Since it's just a check, a rescue clause was added in order to always return a boolean.

Apply constructor fn before checking validity of input

---

lib/dry/types/constructor.rb
spec/dry/types/constructor_spec.rb

Consequent calls of `.constructor` lead to right-to-left composition i.e. the block you're passing will be called _after_ the underlying constructor. Sometimes you want to prepend a block, that's what `Constructor#prepend` does. I also added Constructor#append as an alias for `#constructor`.
I believe this addresses #258
@solnic @timriley are you happy with names? E.g. it can be before/after

Add Constructor#{prepend,append}

---

lib/dry/types/core.rb

Both [`lib/dry/types/core.rb:30`](#diff-eb310b9f51700ccb1cb335c0dad7b7ffL30) and [`lib/dry/types/core.rb:35`](#diff-eb310b9f51700ccb1cb335c0dad7b7ffL35) register all primitives and not only those that are non-coercible through kernel methods.
Also I have described constants and used links to them to simplify descriptions of what has been registered.

Fix descriptions of types registered

---

lib/dry/types/constructor.rb
spec/dry/types/constructor_spec.rb

`Dry::Types['coercible.integer']` uses `Integer()` as a constructor, which raises `ArgumentError` if it can't coerce the input.
`Dry::Types::Constructor#valid?` only caught `TypeError` and `NoMethodError`, so it would raise for checking the validity of an invalid integer.

fix detecting invalid integers

---

lib/dry/types/default.rb
spec/dry/types/default_spec.rb
spec/dry/types/sum_spec.rb

@flash-gordon 
The issue was found in https://github.com/dry-rb/dry-struct/issues/90
Do not return the default value when passing `nil`

do not return default value if nil is passed

---

Gemfile
bin/console
lib/dry/types.rb
lib/dry/types/any.rb
lib/dry/types/builder.rb
lib/dry/types/constrained.rb
lib/dry/types/constructor.rb
lib/dry/types/default.rb
lib/dry/types/definition.rb
lib/dry/types/enum.rb
lib/dry/types/extensions/maybe.rb
lib/dry/types/hash.rb
lib/dry/types/hash/schema.rb
lib/dry/types/printer.rb
lib/dry/types/result.rb
lib/dry/types/safe.rb
lib/dry/types/spec/types.rb
lib/dry/types/sum.rb
spec/dry/types/array_spec.rb
spec/dry/types/constrained_spec.rb
spec/dry/types/constructor_spec.rb
spec/dry/types/default_spec.rb
spec/dry/types/definition_spec.rb
spec/dry/types/enum_spec.rb
spec/dry/types/hash_spec.rb
spec/dry/types/map_spec.rb
spec/dry/types/safe_spec.rb
spec/dry/types/schema_spec.rb
spec/dry/types/sum_spec.rb
spec/spec_helper.rb

Addresses #290 
This is a WIP. The goal is to print only what needs to be print. I disabled the default `inspect/to_s` implementation coming from dry-equalizer and replaced it with a custom traversing object.

Add type printer with better type introspection

---

Gemfile
lib/dry/types/hash.rb
lib/dry/types/schema.rb
spec/dry/types/schema_spec.rb

It'll be useful for dry-struct where new struct can be created based on existing ones. Now we can check only new keys and skip type application for previously existed.

Add option for ignoring missing keys

---

.travis.yml

Updates the matrix to use latest Rubies.
Removes an old setting from Travis. See https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration

CI: Use latest Rubies, drop sudo: false setting

---

.travis.yml

This PR updates the CI matrix to use latest JRuby, **9.2.7.0**.
[JRuby 9.2.7.0 release blog post](https://www.jruby.org/2019/04/09/jruby-9-2-7-0.html)

CI: latest jruby-9.2.7.0

---

lib/dry/types/errors.rb
lib/dry/types/map.rb
lib/dry/types/nominal.rb
lib/dry/types/schema.rb
spec/dry/types/schema_spec.rb

This brings sanity back to errors handling. I had to add some defensive programming in order to ensure all errors and failure objects have the same interface. It's possible to improve it further but even in this form it's 1000% better than before.

Handle all errors consistently

---

lib/dry/types/constructor.rb
lib/dry/types/constructor/call.rb
lib/dry/types/constructor/function.rb
lib/dry/types/printer.rb
spec/dry/types/compiler_spec.rb
spec/dry/types/constructor/function_spec.rb

It is possible to save some allocations along the way. For this, we'll need a first class representation of the constructor function.

Performance improvements for constructor types

---

lib/dry/types/compiler.rb
lib/dry/types/constructor/function.rb
spec/dry/types/compiler_spec.rb
spec/dry/types/constructor/function_spec.rb
spec/dry/types/to_ast_spec.rb

Now AST can be serialzied and deserialized if it uses only globally accessible constructor functions. This is a robust requirement.

Make AST represenation of constructor functions more precise

---

lib/dry/types/array/member.rb
lib/dry/types/coercions/params.rb
lib/dry/types/constrained.rb
lib/dry/types/constrained/coercible.rb
lib/dry/types/constructor.rb
lib/dry/types/constructor/function.rb
lib/dry/types/default.rb
lib/dry/types/enum.rb
lib/dry/types/extensions/maybe.rb
lib/dry/types/lax.rb
lib/dry/types/map.rb
lib/dry/types/nominal.rb
lib/dry/types/printer.rb
lib/dry/types/schema.rb
lib/dry/types/schema/key.rb
lib/dry/types/sum.rb
lib/dry/types/type.rb
spec/dry/types/constrained_spec.rb
spec/dry/types/constructor/function_spec.rb

The idea is to choose the execution path in the top-level type. This PR also eliminates super calls in functions of constructor types, makes them faster for free.
```
$ bundle exec ruby benchmarks/schema_valid_vs_invalid.rb 
Warming up --------------------------------------
valid input    84.216k i/100ms
invalid input    85.912k i/100ms
Calculating -------------------------------------
valid input      1.088M (± 3.7%) i/s -      5.474M in   5.037302s
invalid input      1.098M (± 1.4%) i/s -      5.498M in   5.006690s
Comparison:
invalid input:  1098412.8 i/s
valid input:  1088334.7 i/s - same-ish: difference falls within error
```

Split call into call_safe and call_unsafe

---

lib/dry/types/compiler.rb
lib/dry/types/constrained.rb
lib/dry/types/constructor.rb
lib/dry/types/decorator.rb
lib/dry/types/default.rb
lib/dry/types/enum.rb
lib/dry/types/lax.rb
lib/dry/types/map.rb
lib/dry/types/meta.rb
lib/dry/types/nominal.rb
lib/dry/types/options.rb
lib/dry/types/printer.rb
lib/dry/types/schema.rb
lib/dry/types/schema/key.rb
lib/dry/types/spec/types.rb
lib/dry/types/sum.rb
spec/dry/types/compiler_spec.rb
spec/dry/types/default_spec.rb
spec/dry/types/enum_spec.rb
spec/dry/types/map_spec.rb
spec/dry/types/schema_spec.rb
spec/dry/types/sum_spec.rb
spec/dry/types/to_ast_spec.rb

This changes the place where metadata is stored by pushing it down to the decorated type. As far as I can tell this is not a significant change, no regression was found in my application, rom & rom-sql are both green except for two specs. OTOH it adds more reliable and predictable behavior when working with metadata: no matter how you embellish your source type, the meta will be preserved:
Before:
```ruby
[1] pry(main)> Types::String.meta(name: :full_name).constructor(&:to_s).meta
=> {}
```
After:
```ruby
[1] pry(main)> Types::String.meta(name: :full_name).constructor(&:to_s).meta
=> {:name=>:full_name}
```
This immediately solves some issues we found in rom while trying to use default types in relation schemas. Besides it, the new behavior looks more ligical and consistent to me.

Push meta down to decorated type

---

lib/dry/types/builder_methods.rb
spec/dry/types/module_spec.rb

This constructs a nominal `Any` with constraints of having given methods
implemented.
Example:
```ruby
Callable = Types::Contract(:call)
Contact = Types::Contract(:name, :address)
```
References #56
**Resources**
[Original
discussion](https://discourse.dry-rb.org/t/support-for-type-classes/759)

Adds `.Contract(*methods)` type constructor

---

CHANGELOG.md
lib/dry/types/builder_methods.rb
spec/dry/types/module_spec.rb

We cannot yet release a new version of dry-logic because dry-schema will be broken in this case. This commit postpones release of this feature until 1.1.0

Postpone release of Types.Contract

---

lib/dry/types/coercions.rb
lib/dry/types/core.rb
lib/dry/types/json.rb
lib/dry/types/params.rb
spec/dry/types/core_spec.rb
spec/dry/types/types/json_spec.rb
spec/dry/types/types/params_spec.rb

I have kept the distinction between kernel or by convention method coercion in the implementation, so it would be easy to separate them as different families if desired in the future.
Closes #47

Add Coercible::Symbol, Params::Symbol & JSON::Symbol

---

lib/dry/types/array.rb
lib/dry/types/array/constructor.rb
lib/dry/types/array/member.rb
lib/dry/types/constructor.rb
lib/dry/types/hash/constructor.rb
lib/dry/types/lax.rb
lib/dry/types/printer.rb
lib/dry/types/schema/key.rb
spec/dry/types/array_spec.rb
spec/dry/types/compiler_spec.rb
spec/dry/types/lax_spec.rb
spec/dry/types/schema_spec.rb

This fixes a few corner cases when using array types. One specific was reported by @solnic 
```ruby
Dry::Types['params.array<params.integer>'].member.('1')
```
Now it works fine. This is the same solution we have for hash constructors so it potentially can be generalized but atm I just want to fix it as it is.

Add Array::Constructor

---

CHANGELOG.md
lib/dry/types/builder_methods.rb
spec/dry/types/module_spec.rb

@waiting-for-dev it's suggested by @solnic. His concern is people may confuse it with `Dry::Validation::Contract`. I don't have an opinion on the matter but if you do, please chime in.

Rename Types.Contract to Types.Interface

---

lib/dry/types/builder_methods.rb
spec/dry/types/module_spec.rb

Addresses https://github.com/dry-rb/dry-schema/issues/171
But this is only part of the solution, the second part is not allowing nested schemas on non-generic types.

Use Types::{Array,Hash} as nominal types in `Constructor` when called with Array and Hash respectively

---

lib/dry/types/params.rb
spec/dry/types/types/params_spec.rb

```ruby
[1] pry(main)> Types::Optional::Params::Integer.('99')
=> 99
[2] pry(main)> Types::Optional::Params::Integer.('')
=> nil
```
Note that `Dry::Types['optional.params.integer']` is not the same as `Types::Params::Integer.optional`. It would be a breaking change, it's also not clear whether we want this.

Add Types::Optional::Params

---

lib/dry/types/extensions.rb
lib/dry/types/extensions/monads.rb
spec/extensions/monads/result_spec.rb

This extension adds `.to_monad` method which replaces `Dry::Types::Result` with `Dry::Monads::Result`:
```ruby
Dry::Types.load_extensions(:monads)
result = Dry::Types['strict.string'].try('Jane')
result.class #=> Dry::Types::Result::Success
monad = result.to_monad
monad.class #=> Dry::Monads::Result::Success
monad.value!  # => 'Jane'
result = Dry::Types['strict.string'].try(nil)
result.class #=> Dry::Types::Failure
monad = result.to_monad
monad.class #=> Dry::Monads::Result::Failure
monad.failure  # => [#<Dry::Types::ConstraintError>, nil]
```
Closes #325

Add monads extension

---

docsite/source/extensions/maybe.html.md

Currently it is not taken as ruby code because the
spaces at the beginning

Fixing codeblock in maybe.html.md

---

lib/dry/types/array/member.rb
spec/dry/types/array_spec.rb

One of the branches was calling `Nominal#failure` with a wrong parameter, and that was causing an exception that should not be happening.
Also adding more spec for `Dry::Types::Array#try`

Fix error on Dry::Types::Array#try

---

docsite/source/extensions/maybe.html.md
docsite/source/hash-schemas.html.md

Two method dots in a row is not valid Ruby.
It looks like the dots were moved to the start of the newlines between:
https://dry-rb.org/gems/dry-types/0.15/hash-schemas/#transforming-types
and 
https://dry-rb.org/gems/dry-types/1.2/hash-schemas/#transforming-types
which resulted in an extra one being left in.

Fix typo in doc: Remove duplicated dot from Hash Schemas example

---

Gemfile
lib/dry/types/builder_methods.rb
spec/dry/types/module_spec.rb

There is no point in doing this. Moreover, Dry::Struct::Constructor doesn't implement all type methods (for some reasons, I guess) and it led to regressions in hanami-model.

Don't build constructors when class implementing type interface given

---

lib/dry/types/coercions.rb
lib/dry/types/coercions/params.rb
spec/dry/types/types/json_spec.rb
spec/dry/types/types/params_spec.rb

It can be useful in tests or similar places where you want to pass a coerced value to a type. However, if you rely on this behavior in production, chances are this is a smell in your code.

Accept Time/Date/DateTime and booleans in JSON and Params types

---

docsite/source/hash-schemas.html.md
lib/dry/types/schema.rb
spec/dry/types/schema_spec.rb

It's also aliased as `.compose`.
I submit this PR in relation with https://github.com/dry-rb/dry-struct/pull/139
It moves composition to the fundamental piece of a `Dry::Struct`, a `Dry::Types::Hash::Schema`.
If this PR is accepted I'll modify the other one accordingly so it makes use of the new method.
Key transformation and type transformation work in a different way due to how they are implemented, but I haven't studied why it is this way. Any feedback is welcomed :)

Add `Dry::Types::Hash::Schema.merge`

---

lib/dry/types/builder.rb
lib/dry/types/lax.rb
lib/dry/types/spec/types.rb
spec/dry/types/array_spec.rb
spec/dry/types/constrained_spec.rb
spec/dry/types/enum_spec.rb
spec/dry/types/map_spec.rb
spec/dry/types/nominal_spec.rb
spec/dry/types/schema_spec.rb
spec/dry/types/sum_spec.rb
spec/dry/types/types/params_spec.rb

This allows not to bother about which kind of type you have and call `.append`/`.prepend` whenever you like. It improves ergonomics for the sake of type interface size. However, these methods are just aliases and shouldn't be a major problem.

Add aliases for .constructor

---

docsite/source/built-in-types.html.md

These are 2 types that I've detected while developing a project.

Include Symbol coercions in docs about built-in types

---

lib/dry/types/core.rb
spec/dry/types/module_spec.rb
spec/dry/types_spec.rb

```ruby
Types::Optional::String # => strict optional string
Dry::Types['optional.integer'] # => strict optional integer
```

Add strict types as default to optional namespace

---

lib/dry/types/params.rb
spec/dry/types/types/params_spec.rb

This type will use `Kernel.String` to cast data to a string

Add Params::String

---

lib/dry/types/params.rb
spec/dry/types/types/params_spec.rb

It broke dry-schema because it gives priority to `params.string` over `strict.string` which makes perfect sense. It's very unsafe to coerce arbitrary input to strings. Params also support other types than strings, like hashes; implicitly casting them to strings is way off. I'm revering this change, users can write their own constructor types where needed.

Revert adding Params::String

---

docsite/source/index.html.md

Small update on the docs for meta usage to show how to get the metadata. Not sure if this is documented somewhere but personally I couldn't find it.
Thank you @solnic  for your support in https://discourse.dry-rb.org/t/how-to-access-meta-fields-in-structs/989

Shows meta usage in intro doc

---

lib/dry/types/predicate_inferrer.rb
spec/dry/types/predicate_inferrer_spec.rb

We have no plans inferring more complex checks ATM. Instead, dry-schema will iterate over schemas keys and add them one-by-one.

Infer hash? predicate for hash schemas

---

lib/dry/types/coercions.rb
lib/dry/types/coercions/json.rb
lib/dry/types/coercions/params.rb
spec/dry/types/types/json_spec.rb

JSON has values for `nil` and `''`: `null` and `""`. Coercion empty strings to `nil` in JSON types is a long-standing bug which some code may rely on by now :( This has to be fixed nonetheless. Ref https://github.com/dry-rb/dry-schema/issues/229

Do not coerce empty strings to nil in json.nil

---

lib/dry/types/meta.rb
lib/dry/types/nominal.rb
lib/dry/types/schema.rb

This PR updates small details in the YARD annotations to make the API docs render with fewer warnings.
There were a few  API docs warnings:
> Building YARD (yri) index for dry-types-1.4.0...
lib/dry/types/meta.rb:14: [UnknownParam] @param tag has unknown parameter name: new_options. Did you mean `options`?
lib/dry/types/schema.rb:86: [UnknownParam] @param tag has unknown parameter name: hash
lib/dry/types/schema.rb:291: [UnknownParam] @param tag has unknown parameter name: schema
lib/dry/types/nominal.rb:101: [UnknownParam] @param tag has unknown parameter name: block

Avoid YARD warnings

---

docsite/source/custom-types.html.md

Add example in `Types.Constructor` on how to use a custom method.
The documentation will now cover the signature of `Types.Constructor(klass, cons = nil, &block)` in full.

Document use of custom method in Constructor

---

docsite/source/custom-types.html.md
docsite/source/hash-schemas.html.md

* Was getting param count errors on Types.Hash(:permissive, name: Types::String) and saw in the source where schema type params like that have been deprecated and raise via call to weak.
* Fixed md for Hash merge schema section.

Docs: Removing Hash schema type param and fixing md section

---

lib/dry/types/printer.rb

Ruby 3 makes labmdas from symbols rather than procs when you `:meth.to_proc`. This is probably for the better.

Update type printer

---

lib/dry/types.rb

We don’t need the whole of the concurrent gem, just this one part of it.
This results in 242 fewer files loaded when requiring “dry/types”.

Cherry-pick “concurrent/map” require

---

lib/dry/types/builder.rb
lib/dry/types/constrained.rb
lib/dry/types/constructor.rb
lib/dry/types/constructor/function.rb
lib/dry/types/constructor/wrapper.rb
lib/dry/types/decorator.rb
lib/dry/types/printer.rb
lib/dry/types/spec/types.rb
spec/dry/types/compiler_spec.rb
spec/dry/types/constrained_spec.rb
spec/dry/types/constructor/wrapper_spec.rb
spec/dry/types/constructor_spec.rb
spec/dry/types/lax_spec.rb
spec/dry/types/module_spec.rb
spec/dry/types/to_ast_spec.rb

This adds support for constructor types that can hook into "type application" by taking control when the block has two parameters:
```ruby
Month = Dry::Types["coercible.integer"].constructor do |input, type|
type.(input) + 1
end
```
Earlier, this could be done with just `.constructor { |input| + 1 }`, however, having control over `type` allows for implementing various fallback strategies:
```ruby
Age = Dry::Types["coercible.integer"].constructor do |input, type|
type.(input) { 18 }
end
Age.('17') # => 17
Age.('foo') # => 18
```
These kinds of constructor blocks also support `prepending` and `appending`. Generally, this interface is akin to the rack's middleware.
A word of warning: constructor types can get tricky, this is especially true for wrapping constructors. For instance, calling …

Wrapping constructor types

---

lib/dry/types/builder.rb
lib/dry/types/default.rb
spec/dry/types/builder_spec.rb
spec/dry/types/default_spec.rb
spec/dry/types/lax_spec.rb

This adds the `.fallback` method that wraps a type with a fallback value or a block. It's different from `.default` since default types make sense only for missing/absent values (e.g. missing keys in schema input). `.fallback` is more general:
```ruby
age = Types::Integer.fallback(18)
age.(20) # => 20
age.("invalid") # => 18
```
In some cases, `.default` and `.fallback` can be used interchangeably but I advise against this since it doesn't always use as you would expect:
```ruby
age.() # => 18
Types::Hash.schema(age: age).({}) # => :age is missing in Hash input
```
Fallbacks are tested to be compatible with dry-schema, see https://github.com/dry-rb/dry-schema/pull/337/files#diff-753532781c2792be1bada750fdaca7f5f8bca2ac6021da8afea8916ae3a02f86
Under the hood, it uses wrapping constructors …

Types with fallback values

---

lib/dry/types/params.rb
spec/dry/types/types/params_spec.rb

Logically, it's no different from strict.string. It seems like dry-schema is fine with the change, I'll do a few more tests, though.

Add params.string

---

lib/dry/types/predicate_inferrer.rb
spec/dry/types/predicate_inferrer_spec.rb

Deprecate predicate inferring from class names

---

lib/dry/types.rb
lib/dry/types/builder.rb
spec/dry/types_spec.rb

Given we have a stable and flexible API for building types I think it's relatively safe to give users a way to define custom type constructors. An even "safer" way would be using refinements but it doesn't look it's worth it.
ref #413, #409

Support for custom builder methods

---

lib/dry/types/constrained.rb
lib/dry/types/constructor.rb
lib/dry/types/constructor/function.rb
lib/dry/types/default.rb
lib/dry/types/enum.rb
lib/dry/types/extensions/maybe.rb
lib/dry/types/nominal.rb
lib/dry/types/sum.rb

Putting these in any file where we refer to Dry::Equalizer should prevent `undefined method 'Equalizer' for Dry:Module` occurring, regardless of the order of requires.
@solnic @flash-gordon Is there any reason these weren't here before? We get the error above today in CI when upgrading a work project to 1.5.0.

Add missing dry/core/equalizer requires

---

lib/dry/types/predicate_registry.rb

2.7 introduced `UnboundMethod#bind_call` which is much faster than
doing `Method.bind(receiver).call`.
And even on older rubies caching `Kernel.instance_method(:respond_to?)`
in a constant will save quite a lot of extra costly allocations.

Optimize PredicateRegistry for Ruby 2.7+

---

lib/dry/types/errors.rb
spec/dry/types/schema_spec.rb

This PR implements `SchemaError#key` & `SchemaError#value`. It makes `SchemaError`s interface more in line with `MissingKeyError`, `UnknownKeysError` & `ConstraintError` which have (most) of their instance variables accessible to the public.

Implement SchemaError#value and SchemaError#key

---

lib/dry/types.rb
spec/dry/types_spec.rb

When using `Dry::Types.loader.eager_load`, Zeitwerk raises more than one error:
```
Zeitwerk::NameError:
expected file .../dry-types/lib/dry/types/compat.rb to define constant Dry::Types::Compat, but didn't
NameError: uninitialized constant Dry::Types::Extensions
.../dry-core/lib/dry/core/deprecations.rb:227:in `block (2 levels) in deprecate_constant'
NameError: uninitialized constant RSpec
from .../dry-types/lib/dry/types/spec/types.rb:3:in `<top (required)>'
```
Add some ignores to prevent this error; add a test that ensures eager loading works.

Zeitwerk fixes

---

.gitignore
lib/dry/types/builder.rb
lib/dry/types/intersection.rb
lib/dry/types/printer.rb
spec/dry/types/intersection_spec.rb

dry-schema and dry-logic both support &. Adding support for & in
dry-types allows for a more expressive type system...
```
module Types
Callable = Interface(:call)
Procable = Interface(:to_proc)
Function = Callable & Procable
end
```
...and greatly simplifies value coercion in dry-schema, where a custom
types merge attempts to simulate an intersection type.

Intersection (&) support redux

---

changelog.yml
dry-types.gemspec
lib/dry/types/version.rb
project.yml

The following ensures BigDecimal is required in the `gemspec` so warnings are resolved when using Ruby 3.3.0. This is backward compatible for all supported Ruby versions of this project.
Resolves #464.

Fixed BigDecimal warning

---

spec/dry/types/default_spec.rb

This test relied on an assumption that is no longer true in 3.3.

Fix test for Ruby 3.3

---

docsite/source/combining-types.html.md
docsite/source/combining-types/sum.html.md
docsite/source/intersection.html.md

I was working on a project and wanted this functionality, happened to just try using `&` and it actually worked -- but discovered that this was still an undocumented feature.
So, I wrote up a short page about it, using an example from my real world project.
I also arranged sum & intersection pages under a "Combining Types" section, and placed it after constraints and hash schemas, since this sort of builds on top of those ideas. I didn't see a way to actually test the docsite generation, so hopefully it looks good.

Added documentation for intersection types

---

lib/dry/types/builder.rb
lib/dry/types/constrained.rb
lib/dry/types/sum.rb
spec/dry/types/predicate_inferrer_spec.rb

Closes #473
Implements the following api for specifying nullary constraints (no additional argument needed, e.g., `:odd`) and unary constraints (additional argument needed, e.g., `gt: 18`).
```ruby
type.constrained(:odd) # new variant
type.constrained(:odd, :even) # new variant
type.constrained(:odd, gt: 200, lt: 300) # new variant
```
The above is covered by new tests and updated yardocs. If this api is acceptable, I will update the docsite accordingly.
The api also accepts the following for backward compatibility. However, I suggest deprecating this behavior as non-intuitive and dependent on a quirk of the former implementation (`#map`). Deprecating will allow for the removal of an otherwise unnecessary application of `Array#flatten` in processing arguments.
```ruby …
```

Provide a consistent interface for specifying nullary constraints

---

lib/dry/types/enum.rb
spec/dry/types/enum_spec.rb

Resolves issue #458 - adds the Dry::Types::Enum#each_value method. 
This is my first contribution to this repository and first code OSS contribution in general - have done my best to follow conventions across the repo, but please let me know if anything needs changing.
Hope this is useful!

Add Dry::Types::Enum#each_value method, with tests

---

lib/dry/types/default.rb
spec/dry/types/default_spec.rb

Fixes instances when a Default type runs `#try` with a failing value.
Closes #469
```ruby
Types::Integer.default(1).try("a")
```

Allows Default to return the right Result
