- README.md
> Update README adding proper repo's URL

- lib/dry/types/builder.rb
- lib/dry/types/core.rb
- lib/dry/types/maybe.rb
- spec/dry/types/constrained_spec.rb
- spec/dry/types/core_spec.rb
- spec/dry/types/default_spec.rb
- spec/dry/types/maybe_spec.rb
See #49 before considering merge
> Rename optional to maybe

- lib/dry/types/coercions/form.rb
Please can I have this change? It's very convenient to have these extra values.
I can refactor, as the values are just repeating and being transformed in some way, but I would need guidance. The codebase is a bit beyond me.
> Capitalised versions of true and false values

- dry-types.gemspec
- lib/dry/types/maybe.rb
- spec/dry/types/core_spec.rb
- spec/dry/types/hash/default_values_spec.rb
- spec/dry/types/hash/symbolized_spec.rb
- spec/dry/types/maybe_spec.rb
After releasing dry-monads we are now able to replace kleisli gem.
> Replace kleisli with dry-monads (closes #80)

- lib/dry/types/coercions/form.rb
- spec/dry/types/types/form_spec.rb
It is no longer possible to coerce 123qwe to 123
> Use coercions from Kernel (closes #86)

- dry-types.gemspec
- lib/dry/types/value.rb
- spec/dry/types/value_spec.rb
> Deep freeze Dry::Types::Value objects

- lib/dry/types/hash/schema.rb
- spec/dry/types/compiler_spec.rb
- spec/dry/types/hash_spec.rb
I'd like to refactor the code in #134 to reduce the massive duplication but the coverage doesn't seem to be great. I'm going to try to add tests and kill dead code in this PR first so that the subsequent refactor is less painful
> Improve coverage of Hash schemas

- benchmarks/hash_schemas.rb
- lib/dry/types/hash/schema.rb
A bit cleaner I think :smile:. As or more performant as the previous implementation
> Refactor hash schemas

- lib/dry/types/extensions/maybe.rb
- spec/extensions/maybe/constrained_spec.rb
- spec/extensions/maybe/core_spec.rb
- spec/extensions/maybe/default_spec.rb
- spec/extensions/maybe/hash_spec.rb
- spec/extensions/maybe/maybe_spec.rb
- spec/spec_helper.rb
> Make Maybe act as default for strict_with_defaults

- lib/dry/types/definition.rb
- lib/dry/types/hash/schema.rb
Hello,
I reduced some allocations. [As you can see][results] this changes improve benchmark about 25%.
[results]: https://gist.github.com/davydovanton/40ddc298496839edc3b11c2adc0086b1
> Reduce memory allocation with simple micro optimizations

- lib/dry/types.rb
- lib/dry/types/array.rb
- lib/dry/types/array/member.rb
- lib/dry/types/builder.rb
- lib/dry/types/coercions.rb
- lib/dry/types/coercions/form.rb
- lib/dry/types/coercions/json.rb
- lib/dry/types/constrained.rb
- lib/dry/types/constrained/coercible.rb
- lib/dry/types/constructor.rb
- lib/dry/types/decorator.rb
- lib/dry/types/default.rb
- lib/dry/types/definition.rb
- lib/dry/types/enum.rb
- lib/dry/types/errors.rb
- lib/dry/types/extensions/maybe.rb
- lib/dry/types/hash.rb
- lib/dry/types/hash/schema.rb
- lib/dry/types/options.rb
- lib/dry/types/safe.rb
- lib/dry/types/sum.rb
- lib/dry/types/type.rb
I have revised these YARD annotations using a tool that instruments your
tests to check types: [yardcheck](https://github.com/backus/yardcheck).
These are the changes I needed to make to make the tool pass.
This is still a WIP because I am trying to also use the great YARD docs in dry-types to help make the tool's recommendations "natural" if that makes sense.
> Make YARD types correct

- lib/dry/types/constrained.rb
- lib/dry/types/definition.rb
- spec/dry/types/constrained_spec.rb
- spec/dry/types/definition_spec.rb
@flash-gordon as discussed this add the equality operator `===` to `Defnition` and `Constrained`, I did not add to other `Types` first I wanted to know your opinion.
> Added case compatibility for Definition and Constrained

- lib/dry/types/definition.rb
- lib/dry/types/sum.rb
- lib/spec/dry/types.rb
> Include meta in equalizers

- CHANGELOG.md
- lib/dry/types/definition.rb
- lib/dry/types/options.rb
- lib/dry/types/sum.rb
- lib/spec/dry/types.rb
- spec/dry/types/sum_spec.rb
This method returns a boolean indicating if type is `Sum` and `left` is `nil`
> Add Type#optinal?

- lib/dry/types/default.rb
- spec/dry/types/default_spec.rb
dry-rb/dry-struct#30 @flash-gordon
> Add type parameter to evaluate default block

- lib/dry/types/array/member.rb
- lib/dry/types/compiler.rb
- lib/dry/types/constrained.rb
- lib/dry/types/constructor.rb
- lib/dry/types/definition.rb
- lib/dry/types/enum.rb
- lib/dry/types/hash/schema.rb
- lib/dry/types/options.rb
- lib/dry/types/safe.rb
- lib/dry/types/sum.rb
- spec/dry/types/compiler_spec.rb
- spec/dry/types/to_ast_spec.rb
> Add meta to the AST

- lib/dry/types/any.rb
- lib/dry/types/constructor.rb
- lib/dry/types/hash/schema.rb
- lib/dry/types/sum.rb
- spec/dry/types/array_spec.rb
- spec/dry/types/constrained_spec.rb
- spec/dry/types/constructor_spec.rb
- spec/dry/types/default_spec.rb
- spec/dry/types/definition_spec.rb
- spec/dry/types/hash_spec.rb
- spec/dry/types/sum_spec.rb
Add Missing Tests and definitions  for case compatibility.
I'm doubting about adding to `Form` and `Json` what do you think?
> Add Missing case compatibility test and definitions

- lib/dry/types/coercions/json.rb
- spec/dry/types/types/json_spec.rb
#215 
@solnic @flash-gordon please review
> Return `Dry::Types::Result::Failure` on `Types::Json::Decimal.try(nil)`

- CONTRIBUTING.md
Just updating the links to point to the right site for discussions!
> Update discussion links

- lib/dry/types/decorator.rb
- spec/dry/types/enum_spec.rb
We are missing the `===` for enum.
This solves it. 😄
> Add === operator to enum type

- dry-types.gemspec
- lib/dry/types.rb
- lib/dry/types/inflector.rb
Solves #226 
Right now `JSON` is not working in `dry-inflector` there is an issue https://github.com/dry-rb/dry-inflector/issues/16
We should decide to merge this PR or wait until the `dry-inflector` part is solve
> Use dry-inflector

- benchmarks/hash_schemas.rb
- lib/dry/types.rb
- lib/dry/types/core.rb
- lib/dry/types/form.rb
- spec/dry/types/array_spec.rb
- spec/dry/types/compiler_spec.rb
- spec/dry/types/constructor_spec.rb
- spec/dry/types/default_spec.rb
- spec/dry/types/enum_spec.rb
- spec/dry/types/hash_constructors/legacy_schema_spec.rb
- spec/dry/types/hash_constructors/symbolized_spec.rb
- spec/dry/types/hash_spec.rb
- spec/dry/types/module_spec.rb
- spec/dry/types/safe_spec.rb
- spec/dry/types/sum_spec.rb
- spec/dry/types/to_ast_spec.rb
- spec/dry/types/types/form_spec.rb
- spec/dry/types/types/json_spec.rb
- spec/extensions/maybe/default_spec.rb
- spec/extensions/maybe/maybe_spec.rb
@flash-gordon @solnic I renamed `int` to `integer`. Hope this helps
> Rename int to integer

- lib/dry/types/builder.rb
- lib/dry/types/compiler.rb
- lib/dry/types/enum.rb
- spec/dry/types/enum_spec.rb
- spec/dry/types/to_ast_spec.rb
See https://github.com/dry-rb/dry-types/pull/160
Thanks @bolshakov, sorry it took a while :)
> Support for enum mapping

- lib/dry/types/compat.rb
- lib/dry/types/compat/int.rb
@flash-gordon I was doing some experimentation and notice the compatibility files were not included.
I guess you planned to add when we reach `1.0`?
> Include compat files

- lib/dry/types/core.rb
- spec/dry/types/core_spec.rb
Fixes #176 
@flash-gordon @solnic I have to say if this all what is needed to add a new type, this library is extremely well designed, I knew it already but just wanted to say 🎉 🎉 to both of you
> Add Range type

- lib/dry/types/constructor.rb
- spec/dry/types/sum_spec.rb
> remove irrelevant super call in Constructor#valid?

- dry-types.gemspec
Add the changelog / bug / source uris to the metadata section for easier
access.
> Add metadata uris

- spec/dry/types/hash_constructors/legacy_schema_spec.rb
- spec/dry/types/schema_spec.rb
- spec/dry/types_spec.rb
> Remove registration of custom types in specs

- lib/dry/types/coercions/params.rb
- spec/dry/types/types/params_spec.rb
> Fix coercion of integers with trailing zero

- lib/dry/types/builder.rb
- spec/dry/types/default_spec.rb
- spec/dry/types/enum_spec.rb
- spec/dry/types/sum_spec.rb
> Print a warning when default value isn't frozen

- lib/dry/types.rb
- lib/dry/types/core.rb
- lib/dry/types/enum.rb
- lib/dry/types/module.rb
- spec/dry/types/module_spec.rb
- spec/dry/types_spec.rb
- spec/spec_helper.rb
> Options for Dry::Types.module

- lib/dry/types/extensions/maybe.rb
- spec/extensions/maybe/maybe_spec.rb
ref https://github.com/rom-rb/rom/issues/519
> Fix Schema::Key.maybe

- lib/dry/types/enum.rb
- spec/dry/types/enum_spec.rb
@solnic this fixes that issue you've found the other day
> Add Builder to Enum

- lib/dry/types/constructor.rb
- lib/dry/types/decorator.rb
- spec/dry/types/constrained_spec.rb
- spec/dry/types/schema_spec.rb
This resolves the issue where metadata wasn't pused "deep enough".
> Fix multi-level delegation

- lib/dry/types/builder_methods.rb
- spec/dry/types/module_spec.rb
> Types.Constructor accepts a type

- lib/dry/types/predicate_inferrer.rb
- lib/dry/types/predicate_registry.rb
- spec/dry/types/predicate_inferrer_spec.rb
- spec/dry/types/predicate_registry_spec.rb
> Add predicate inferrer

- spec/dry/types/predicate_inferrer_spec.rb
- spec/dry/types/primitive_inferrer_spec.rb
> Remove duplicated false type spec

- lib/dry/types/extensions/maybe.rb
- spec/extensions/maybe/maybe_spec.rb
It wasn't tested and the code was wrong.
> Fix behavior of Maybe#call_safe

- lib/dry/types/meta.rb
- lib/dry/types/schema/key.rb
- lib/dry/types/sum.rb
`nil` is inconsistent with dry-struct so I decided to fix it
> Change default types in #meta to Undefined

- Gemfile
- lib/dry/types/schema/key.rb
- spec/dry/types/schema/key_spec.rb
> Fix Schema::Key#optional

- lib/dry/types/schema.rb
- spec/dry/types/schema_spec.rb
> Add Schema#clear

- docsite/source/custom-types.html.md
Fix the documentation bug I introduced in dry-rb/dry-types#401
> Fix Constructor custom method documentation

- docsite/source/extensions/maybe.html.md
- docsite/source/extensions/monads.html.md
I noticed the documentation for `Maybe` was pretty outdated. I went through and fixed that. I also improved formatting for the codeblocks, to make them easier to scan. I added some text explaining more about each of the extensions as well. 
I may not have gotten the text 100% accurate, so please review the text. Aiming for clarity and accuracy!
> [docsite] Improve extensions docs

- docsite/source/extensions/maybe.html.md
- docsite/source/extensions/monads.html.md
Oops I broke the docsite in #434. I think this should fix it
> [docsite] Fix links

- docsite/source/extensions/monads.html.md
#435 wasn't enough :/
It'd be great if CI checked the build for `dry-rb/dry-rb.org` too
> [docsite] Remove quotes from link

- Gemfile
- changelog.yml
- lib/dry/types.rb
- lib/dry/types/container.rb
- project.yml
- Use container from dry-core
- Update changelog
> Switch to using container from dry-core

- docsite/source/custom-type-builders.html.md
> Fixes typo
